# MLP from scratch -- Using Numpy & Pandas

### This module tries to explain the working mechanism of a deep learning neural network and it's training process.
- This a MLP for digit recognition using mnist_train.csv as training dataset.
- There are 3 models having varying number of hidden layers -- 0,1 and 2
- In one cycle (epoch), all the training data is passed through the network, as one sample at a time.
-  The weights are initialized at the beginning of the training process, and keeps on updating until the training epochs are finished.
- The cost value is calculated for each epochs as an indication for evaluating the training process.

In [2]:
import numpy as np
import pandas as pd

In [2]:
#Q1 Extracting the data

def path(file_):
    data=pd.read_csv(file_)
    y = np.array(data['label'])
    y=y.reshape(-1,1)

    x=np.array(data)
    x=np.delete(x, 0 ,axis=1)

    

    print('Shape of pixel-matrix: \n', x.shape)
    print('\n Shape of data-label: \n',y.shape)
    
    return (
        x,
        y
    )
    
x,y =path('mnist_train.csv') 
print(x,'\n')
print(y)

Shape of pixel-matrix: 
 (60000, 784)

 Shape of data-label: 
 (60000, 1)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 

[[5]
 [0]
 [4]
 ...
 [5]
 [6]
 [8]]


In [3]:
# Q2 Zero Hidden layer Neural Network

# Setting up parameters
x_normalized=x/255
weights_ = np.random.uniform(low=-0.1, high=0.1, size=(10, 784))
bias_ = np.ones((10,1))


def zero_layer_model(x_value, y_value, weight_matrix, bias_matrix, learning_rate, num_epochs):
    
 for number in range(num_epochs):   
    total_cost = 0  # Initialize the total cost for tracking across all samples
    
    for a in range(len(x_value)):
        input_layer = x_value[a]

        # True labels which contain accurate probability values
        true_label = np.zeros(10)
        true_label[y_value[a]] = 1
        true_label = true_label.reshape(-1, 1)

        # Calculate the result for the output layer
        result = np.dot(weight_matrix, input_layer.reshape(-1, 1)) + bias_matrix

        # Applying softmax function to the output
        softmax_probs = np.exp(result - np.max(result, axis=0, keepdims=True))
        predict_label = softmax_probs / np.sum(softmax_probs, axis=0, keepdims=True)

        # Gradient descent
        error = predict_label - true_label

        # Compute the cost for the current sample
        cost_function = -np.sum(true_label * np.log(predict_label))
        total_cost += cost_function  # Accumulate the cost

        # Update weights and bias
        weight_matrix -= learning_rate * np.dot(error, input_layer.reshape(1, -1))
        bias_matrix -= learning_rate * error

    print(f'Cost value for {number+1}st epoch: {total_cost / len(x_value)}')
 
 return weight_matrix , bias_matrix
     

updated_weights , updated_bias = zero_layer_model( x_normalized, y, weights_, bias_, 0.05, 50)
print(f'Updated weights: \n{updated_weights} \n Shape: {updated_weights.shape}')
print(f'Updated bias: \n{updated_bias} \n Shape: {updated_bias.shape}')

Cost value for 1st epoch: 0.47909987478357463
Cost value for 2st epoch: 0.4449511523266901
Cost value for 3st epoch: 0.4322410945838628
Cost value for 4st epoch: 0.42521577407324085
Cost value for 5st epoch: 0.42066621232435314
Cost value for 6st epoch: 0.41736616680872973
Cost value for 7st epoch: 0.41490423358537104
Cost value for 8st epoch: 0.4128708686931252
Cost value for 9st epoch: 0.4111134288116357
Cost value for 10st epoch: 0.4095655844745167
Cost value for 11st epoch: 0.40820334557031146
Cost value for 12st epoch: 0.40700615355094105
Cost value for 13st epoch: 0.40595065865404684
Cost value for 14st epoch: 0.40501095625580014
Cost value for 15st epoch: 0.4041631648385757
Cost value for 16st epoch: 0.40339083129324954
Cost value for 17st epoch: 0.40268264409602994
Cost value for 18st epoch: 0.4020292683554547
Cost value for 19st epoch: 0.4014230872509538
Cost value for 20st epoch: 0.4008582927698774
Cost value for 21st epoch: 0.4003300147004495
Cost value for 22st epoch: 0.399

In [4]:
#Q3 Single layer neural network

print("Using sigmoid for One-layer network: \n")
# Setting n-dim of hidden layer as 10
n=10

# Setting up the parameters
x_normalized = x/255
weights_01 = np.random.uniform(low=-0.1, high=0.1, size=(n, 784))
bias_01 = np.ones((n,1))
weights_02 = np.random.uniform(low=-0.1, high=0.1, size=(10, n))
bias_02 = np.ones((10,1))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def one_layer_model(x_value, y_value, weight_input, bias_layer, weight_layer, bias_output, learning_rate, num_epochs):
 for number in range(num_epochs):
    total_cost = 0
    
    for a in range(0, len(x)):
        input_layer = x_value[a]

        # True labels which contain accurate prob. values
        true_label = np.zeros(10)
        true_label[y_value[a]] = 1
        true_label = true_label.reshape(-1, 1)

        result_01 = np.dot(weight_input, input_layer.reshape(-1, 1)) + bias_layer

        # HIDDEN LAYER 01
        # sigmoid activation
        sigmoid_ = sigmoid(result_01)

        result_02 = np.dot(weight_layer, sigmoid_) + bias_output

        # Applying softmax function to output result
        softmax_probs = np.exp(result_02 - np.max(result_02, axis=0, keepdims=True))
        predict_label = softmax_probs / np.sum(softmax_probs, axis=0, keepdims=True)

        # Gradient descent
        error = predict_label - true_label
        cost_function = -np.sum(true_label * np.log(predict_label))
        total_cost+=cost_function

        # Backpropagation
        delta_output = error
        delta_hidden = np.dot(weight_layer.T, delta_output) * sigmoid_derivative(sigmoid_)

        # Weight and bias updates
        weight_input -= learning_rate * np.dot(delta_hidden, input_layer.reshape(1, -1))
        bias_layer -= learning_rate * delta_hidden

        weight_layer -= learning_rate * np.dot(delta_output, sigmoid_.reshape(1, -1))
        bias_output -= learning_rate * delta_output
    
    print(f'Cost value for {number} epoch: {total_cost / len(x_value)}')    


# Executing the model

one_layer_model(x_normalized, y, weights_01, bias_01, weights_02, bias_02, 0.05, 50)


Using sigmoid for One-layer network: 

Cost value for 0 epoch: 0.4141565834741365
Cost value for 1 epoch: 0.3140623311965506
Cost value for 2 epoch: 0.2946662086380497
Cost value for 3 epoch: 0.28230739972401175
Cost value for 4 epoch: 0.27295896876526626
Cost value for 5 epoch: 0.26624792283251353
Cost value for 6 epoch: 0.2614574038578359
Cost value for 7 epoch: 0.25650617869980047
Cost value for 8 epoch: 0.2504630875148965
Cost value for 9 epoch: 0.24778992200501715
Cost value for 10 epoch: 0.2454692856368682
Cost value for 11 epoch: 0.24264708745680894
Cost value for 12 epoch: 0.24061943202530328
Cost value for 13 epoch: 0.2387336523205641
Cost value for 14 epoch: 0.23780270861287697
Cost value for 15 epoch: 0.2354844744655284
Cost value for 16 epoch: 0.22946136120983868
Cost value for 17 epoch: 0.22986238434186831
Cost value for 18 epoch: 0.2276140548102131
Cost value for 19 epoch: 0.2272449174371994
Cost value for 20 epoch: 0.22581366431794764
Cost value for 21 epoch: 0.225037753

In [5]:
#Q4 Two layer neural network

print("Using sigmoid for Two-layer network: \n")
# Setting n-dim of hidden layer 01 as 10
n = 10
# Setting n-dim of hidden layer 02 as 10
m = 10

# Setting up the parameters
x_normalized = x/255

weights_01 = np.random.uniform(low=-0.1, high=0.1, size=(n, 784))
bias_01 = np.ones((n, 1))

weights_02 = np.random.uniform(low=-0.1, high=0.1, size=(m, n))
bias_02 = np.ones((m, 1))

weights_03 = np.random.uniform(low=-0.1, high=0.1, size=(10, m))
bias_03 = np.ones((10, 1))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def two_layer_model(x_value, y_value, weight_input, bias_layer01, weight_layer01, bias_layer02, weight_layer02, bias_output, learning_rate, num_epochs):
  for number in range(num_epochs):
    total_cost = 0    
    
    for a in range(0, len(x)):
        input_layer = x_value[a]

        # True labels which contain accurate prob. values
        true_label = np.zeros(10)
        true_label[y_value[a]] = 1
        true_label = true_label.reshape(-1, 1)

        result_01 = np.dot(weight_input, input_layer.reshape(-1, 1)) + bias_layer01

        # HIDDEN LAYER 01
        # sigmoid activation
        sigmoid_01 = sigmoid(result_01)

        result_02 = np.dot(weight_layer01, sigmoid_01) + bias_layer02

        # HIDDEN LAYER 02
        # sigmoid activation
        sigmoid_02 = sigmoid(result_02)

        result_03 = np.dot(weight_layer02, sigmoid_02) + bias_output

        # Applying softmax function to output result
        softmax_probs = np.exp(result_03 - np.max(result_03, axis=0, keepdims=True))
        predict_label = softmax_probs / np.sum(softmax_probs, axis=0, keepdims=True)

        # Gradient descent
        error = predict_label - true_label
        cost_function = -np.sum(true_label * np.log(predict_label))
        total_cost+=cost_function

        # Backpropagation
        delta_output = error
        delta_hidden02 = np.dot(weight_layer02.T, delta_output) * sigmoid_derivative(sigmoid_02)
        delta_hidden01 = np.dot(weight_layer01.T, delta_hidden02) * sigmoid_derivative(sigmoid_01)

        # Weight and bias updates
        weight_input -= learning_rate * np.dot(delta_hidden01, input_layer.reshape(1, -1))
        bias_layer01 -= learning_rate * delta_hidden01

        weight_layer01 -= learning_rate * np.dot(delta_hidden02, sigmoid_01.reshape(1, -1))
        bias_layer02 -= learning_rate * delta_hidden02

        weight_layer02 -= learning_rate * np.dot(delta_output, sigmoid_02.reshape(1, -1))
        bias_output -= learning_rate * delta_output

    print(f'Cost value for {number} epoch: {total_cost / len(x_value)}')

# Executing the model
two_layer_model(x_normalized, y, weights_01, bias_01, weights_02, bias_02, weights_03, bias_03, 0.05, 50)

Using sigmoid for Two-layer network: 

Cost value for 0 epoch: 0.7833775457217136
Cost value for 1 epoch: 0.3362386604676637
Cost value for 2 epoch: 0.29892697717185035
Cost value for 3 epoch: 0.282213341183755
Cost value for 4 epoch: 0.2703618216182078
Cost value for 5 epoch: 0.26230960035208856
Cost value for 6 epoch: 0.25604051362073776
Cost value for 7 epoch: 0.2500980903348335
Cost value for 8 epoch: 0.24256268292869146
Cost value for 9 epoch: 0.2439068659855273
Cost value for 10 epoch: 0.23481809622600602
Cost value for 11 epoch: 0.2364105375559642
Cost value for 12 epoch: 0.23027428415676468
Cost value for 13 epoch: 0.22977376380014575
Cost value for 14 epoch: 0.22847267926800172
Cost value for 15 epoch: 0.2216786580605916
Cost value for 16 epoch: 0.22138494427500766
Cost value for 17 epoch: 0.22414757235876123
Cost value for 18 epoch: 0.21787340523754484
Cost value for 19 epoch: 0.21634092410092326
Cost value for 20 epoch: 0.2175156866762039
Cost value for 21 epoch: 0.215944003

## Momentum in Neural Networks

Momentum is a technique that helps accelerate gradient descent in directions of consistent decrease while damping oscillations in directions with high curvature. It achieves this by incorporating a fraction of the previous weight update into the current update.

## How Momentum Works in Gradient Descent

### Without Momentum (Standard Gradient Descent)

**Update Rule:**

$$
w = w - \eta \cdot \nabla J(w)
$$

**Where:**
- $w$: Weights
- $\eta$: Learning rate
- $\nabla J(w)$: Gradient of the cost function \(J(w)\) with respect to \(w\)

---

### With Momentum

Momentum introduces a velocity term \(v\) that smoothens updates:

**Equations:**

$$
v = \beta \cdot v - \eta \cdot \nabla J(w)
$$

$$
w = w + v
$$

**Where:**
- $v$: Velocity (stores the previous updates)
- $\beta$: Momentum coefficient (commonly \(0.9\))
- $\eta$: Learning rate
- $\nabla J(w)$: Gradient of the cost function \(J(w)\) with respect to \(w\)

---

### Key Differences

- **Standard Gradient Descent:** Directly uses the gradient to update weights.
- **With Momentum:** Accumulates gradients (scaled by \(\beta\)) to smooth updates and prevent oscillations.

### Benefits of Momentum

1.  Accelerates convergence on steep slopes.
2.  Reduces oscillations in directions with high curvature.
3.  Helps escape shallow local minima or plateaus.

In [11]:
#Q6 Adding momentum and ReLU function to the previous question

# Setting n-dim of hidden layer 01 as 10
n = 10
# Setting n-dim of hidden layer 02 as 10
m = 10

# Setting up the parameters
x_normalized = x/255

weights_01 = np.random.randn(n, 784) * np.sqrt(2 / 784)
weights_02 = np.random.randn(m, n) * np.sqrt(2 / n)
weights_03 = np.random.randn(10, m) * np.sqrt(2 / m)

bias_01 = np.ones((n, 1))
bias_02 = np.ones((m, 1))
bias_03 = np.ones((10, 1))

def ReLU(x):
    return np.maximum(0, x)

def ReLU_derivative(x):
    return np.where(x > 0, 1, 0)


def two_layer_model(x_value, y_value, weight_input, bias_layer01, weight_layer01, bias_layer02, weight_layer02, bias_output, learning_rate, momentum, epochs):
    # Initialize velocities to zero
    weight_input_velocity = np.zeros((n, 784))
    bias_layer01_velocity = np.zeros((n, 1))
    weight_layer01_velocity = np.zeros((m, n))
    bias_layer02_velocity = np.zeros((m, 1))
    weight_layer02_velocity = np.zeros((10, m))
    bias_output_velocity = np.zeros((10, 1))

    for epoch in range(epochs):
        total_cost = 0
        
        for a in range(len(x_value)):
            input_layer = x_value[a]

            # True labels which contain accurate prob. values
            true_label = np.zeros(10)
            true_label[y_value[a]] = 1
            true_label = true_label.reshape(-1, 1)

            result_01 = np.dot(weight_input, input_layer.reshape(-1, 1)) + bias_layer01

            # HIDDEN LAYER 01
            # ReLU activation
            ReLU_01 = ReLU(result_01)

            result_02 = np.dot(weight_layer01, ReLU_01) + bias_layer02

            # HIDDEN LAYER 02
            # ReLU activation
            ReLU_02 = ReLU(result_02)

            result_03 = np.dot(weight_layer02, ReLU_02) + bias_output

            # Applying softmax function to output result
            softmax_probs = np.exp(result_03 - np.max(result_03, axis=0, keepdims=True))
            predict_label = softmax_probs / np.sum(softmax_probs, axis=0, keepdims=True)

            # Gradient descent
            error = predict_label - true_label
            epsilon = 1e-12  # A very small number
            cost_function = -np.sum(true_label * np.log(predict_label + epsilon))
            total_cost+=cost_function

            # Backpropagation
            delta_output = error
            delta_hidden02 = np.dot(weight_layer02.T, delta_output) * ReLU_derivative(ReLU_02)
            delta_hidden01 = np.dot(weight_layer01.T, delta_hidden02) * ReLU_derivative(ReLU_01)

            # Weight and bias updates with momentum
            weight_input_velocity = momentum * weight_input_velocity - learning_rate * np.dot(delta_hidden01, input_layer.reshape(1, -1))
            bias_layer01_velocity = momentum * bias_layer01_velocity - learning_rate * delta_hidden01

            weight_layer01_velocity = momentum * weight_layer01_velocity - learning_rate * np.dot(delta_hidden02, ReLU_01.reshape(1, -1))
            bias_layer02_velocity = momentum * bias_layer02_velocity - learning_rate * delta_hidden02

            weight_layer02_velocity = momentum * weight_layer02_velocity - learning_rate * np.dot(delta_output, ReLU_02.reshape(1, -1))
            bias_output_velocity = momentum * bias_output_velocity - learning_rate * delta_output

            weight_input += weight_input_velocity
            bias_layer01 += bias_layer01_velocity

            weight_layer01 += weight_layer01_velocity
            bias_layer02 += bias_layer02_velocity

            weight_layer02 += weight_layer02_velocity
            bias_output += bias_output_velocity
        
        print(f'Cost value for {epoch} epoch: {total_cost / len(x_value)}')    

    # Returning the resulting weights after training
    return (
        weight_input,
        bias_layer01,
        weight_layer01,
        bias_layer02,
        weight_layer02,
        bias_output
    )

learning_rate = 0.05
momentum = 0.8
epochs = 50

resulting_weights = two_layer_model(x_normalized, y, weights_01, bias_01, weights_02, bias_02, weights_03, bias_03, learning_rate, momentum, epochs)

# Print the resulting weights
print('\nResulting Weights:\n')
print('Weight_Input: \n', resulting_weights[0])
print('\n Bias_Layer01: \n', resulting_weights[1])
print(' \n Weight_Layer01: \n', resulting_weights[2])
print('\n Bias_Layer02: \n', resulting_weights[3])
print('\n Weight_Layer02: \n', resulting_weights[4])
print('\n Bias_Output: \n', resulting_weights[5])


Cost value for 0 epoch: 2.365295429828174
Cost value for 1 epoch: 2.3650035811707557
Cost value for 2 epoch: 2.3650035811707557
Cost value for 3 epoch: 2.3650035811707557
Cost value for 4 epoch: 2.3650035811707557
Cost value for 5 epoch: 2.3650035811707557
Cost value for 6 epoch: 2.3650035811707557
Cost value for 7 epoch: 2.3650035811707557
Cost value for 8 epoch: 2.3650035811707557
Cost value for 9 epoch: 2.3650035811707557
Cost value for 10 epoch: 2.3650035811707557
Cost value for 11 epoch: 2.3650035811707557
Cost value for 12 epoch: 2.3650035811707557
Cost value for 13 epoch: 2.3650035811707557
Cost value for 14 epoch: 2.3650035811707557
Cost value for 15 epoch: 2.3650035811707557
Cost value for 16 epoch: 2.3650035811707557
Cost value for 17 epoch: 2.3650035811707557
Cost value for 18 epoch: 2.3650035811707557
Cost value for 19 epoch: 2.3650035811707557
Cost value for 20 epoch: 2.3650035811707557
Cost value for 21 epoch: 2.3650035811707557
Cost value for 22 epoch: 2.3650035811707557